USE [master]
GO

/****** Object:  Database [IP-Final]    Script Date: 2/6/2020 11:25:24 PM ******/
CREATE DATABASE [IP-Final]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IP-Final', FILENAME = N'C:\Users\Angel\IP-Final.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'IP-Final_log', FILENAME = N'C:\Users\Angel\IP-Final_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IP-Final].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [IP-Final] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [IP-Final] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [IP-Final] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [IP-Final] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [IP-Final] SET ARITHABORT OFF 
GO

ALTER DATABASE [IP-Final] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [IP-Final] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [IP-Final] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [IP-Final] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [IP-Final] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [IP-Final] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [IP-Final] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [IP-Final] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [IP-Final] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [IP-Final] SET  DISABLE_BROKER 
GO

ALTER DATABASE [IP-Final] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [IP-Final] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [IP-Final] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [IP-Final] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [IP-Final] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [IP-Final] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [IP-Final] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [IP-Final] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [IP-Final] SET  MULTI_USER 
GO

ALTER DATABASE [IP-Final] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [IP-Final] SET DB_CHAINING OFF 
GO

ALTER DATABASE [IP-Final] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [IP-Final] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [IP-Final] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [IP-Final] SET QUERY_STORE = OFF
GO

USE [IP-Final]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [IP-Final] SET  READ_WRITE 
GO

